# These are the funding platforms GitHub currently supports.

github: [zetaprime28] # Replace with your GitHub username if you'd like to use GitHub Sponsors.

# Supported external funding platforms:
patreon: your-patreon-username
open_collective: your-open-collective-username
ko_fi: your-kofi-username
tidelift: your-tidelift-id
community_bridge: your-community-bridge-id
liberapay: your-liberapay-username
issuehunt: your-issuehunt-id
otechie: your-otechie-id
custom: ["https://your-custom-donation-link.com"]
